{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2galaxy
  version: {{ version }}

source:
  path: ../..

build:
  script: make install
  entry_points:
  - q2galaxy=q2galaxy.__main__:root

requirements:
  host:
    - python  {{ python }}
    - setuptools

  run:
    - python  {{ python }}
    - qiime2 {{ qiime2_epoch }}.*
    # Don't include this because it isn't available on staging yet.
    # - q2-mystery-stew {{ release }}.*
    - click
    - lxml

test:
  requires:
    - qiime2 >={{ qiime2 }}

  imports:
    - q2galaxy
  # remove this test until q2-mystery-stew is available
  # commands:
  #   - q2galaxy template tests $(mktemp -d)

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
